#spring:
#  main:
#    log-startup-info: false

##    spring.jackson.date-format= # For instance, `yyyy-MM-dd HH:mm:ss`.
##    spring.jackson.default-property-inclusion= # Controls the inclusion of properties during serialization.
#    spring.jackson.deserialization.*= true # Jackson on/off features for deserialization.
#    spring.jackson.generator.*= true # Jackson on/off features for generators.
##    spring.jackson.joda-date-time-format= # Joda date time format string.
##    spring.jackson.locale= # Locale used for formatting.
#    spring.jackson.mapper.*= true # Jackson general purpose on/off features.
#    spring.jackson.parser.*= true # Jackson on/off features for parsers.
##    spring.jackson.property-naming-strategy= PropertyNamingStrategy.
#    spring.jackson.serialization.*= true # Jackson on/off features for serialization.
##    spring.jackson.time-zone= #  Time zone
##    spring.jackson.visibility.*= # To limit which methods (and fields) are auto-detected.
#  jackson:
#
#    property-naming-strategy: UPPER_CAMEL_CASE
#    serialization:
#      indent-output: true
